version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: |
          pip3 install black --user
          black --check .
      - run: |
          pip3 install flake8 --user
          flake8 .
  build:
    working_directory: ~/work/
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip gmsh
      - run: pip3 install -U pytest pytest-cov excode black flake8
      - checkout
      - run: LANG=C.UTF-8 pip3 install .
      - run: LANG=C.UTF-8 pip3 install -r test_requirements.txt
      # The actual test
      - run: excode README.md test/readme_test.py --filter python,test
      # OMPI doesn't work in chroot by default, cf.
      # <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=494046>
      - run: cd test/ && MPLBACKEND=Agg OMPI_MCA_plm_rsh_agent=/bin/false pytest ../examples . --cov pyfvm
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
